flags: {}
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- servant-checked-exceptions-1.0.0.0
- string-conversions-0.3.0.3
resolver: lts-8.17
